services:
  worker:
    build:
      context: .
      target: runner
    env_file:
      - .env.production
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: on-failure