services:
  worker:
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - '27018:27017'
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
